machine-drivers/docker-machine-driver-xhyve

- README.md
- vmnet/vmnet.go
- xhyve.go
Auto-create NFS share
Missing:
* Validate created `/etc/exports` using `ntpd checkexports` and only overwrite when valid
* Remove from `/etc/exports` on `rm`
Fixes https://github.com/zchee/docker-machine-xhyve/issues/20
```
$ docker-machine -D create -d xhyve --xhyve-disk-size "2000" --xhyve-experimental-nfs-share xhyve 
```
```
docker@boot2docker:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   896.6M    123.8M    772.8M  14% /
tmpfs                   498.1M         0    498.1M   0% /dev/shm
/dev/vda1               996.5M      1.8M    926.5M   0% /mnt/vda1
cgroup                  498.1M         0    498.1M   0% /sys/fs/cgroup
192.168.64.1:/Users     111.9G     84.1G     27.5G  75% /Users
/dev/vda1               996.5M      1.8M    926.5M …
```
> Experimental: Auto-create NFS share

- README.md
The cli shows the memory flag as --xhyve-memory.
Not sure if this is a docs bug or a bug in the driver since the ENV variable seems to look for XHYVE_MEMORY_SIZE
> Update README for memory command

- README.md
- xhyve.go
It seems other drivers use the --driver-memory-size flag, so we should match that. Re-fix the docs to match the correct flag which now exists in the codebase.
> Use --xhyve-memory-size to match other docker-machine drivers

- xhyve.go
Looks like https://github.com/zchee/docker-machine-driver-xhyve/pull/26 broken the machine creation. This fixes it for me.
> Fixed xhyve-memory-size

- xhyve.go
Before only `<nil>` was printed, which didn't really help finding the error.
> Fixes xhyve stdout and stderr printing

- Godeps/Godeps.json
- vendor/github.com/johanneswuerbach/nfsexports/.travis.yml
- vendor/github.com/johanneswuerbach/nfsexports/README.md
- vendor/github.com/johanneswuerbach/nfsexports/nfsexports.go
* Auto-creates `/etc/exports`, which auto-starts nfsd on OS X
* Various line break merging fixes
> Auto-create missing exports file, line break fixes

- xhyve.go
The help states `Number of CPUs for the machine (-1 to use the number of CPUs available)`, but this wasn't actually implemented yet.
> Actually support CPU -1 for all available CPUs

- version.go
- travis need binary owner is `travis:staff` on GitHub releases
> Back to version 0.1.0

- .travis.yml
- In the case of github release, Travis must binary owner is a `travis:staff`
- Add multiple Go version release for debug
> Fix binary owner to travis:staff and Add multiple Go version release

- README.md
- xhyve/xhyve.go
See also https://github.com/zchee/docker-machine-driver-xhyve/pull/75
> Add check binary owner on PreCreateCheck()

- xhyve/xhyve.go
- xhyve/xhyve_test.go
- GetURL, PreCreateCheck, Start, Stop, Restart
> Add PreCommandCheck

- xhyve/version.go
Bug is still exists, but https://github.com/zchee/docker-machine-driver-xhyve/pull/78 for install use homebrew user.
> Bump version to 0.2.2

- xhyve/xhyve.go
501 is often, but not always, the uid of the user on OS X. For instance in our corp environment, our uid is the same as our active directory id. This new check should be more reliable, as 0 is always the uid of the root user.
> fix check for binary root ownership

- xhyve/xhyve.go
Currently for NFS shares the driver maps the remote `root` user to the local `root` user
This causes issues where all files created by the remote are owned by local root and are unaccessible without modifying permissions.
I have changed the NFS mount to map **all** remote users to the current user, this means that files created by the remote now has the same permissions as the local user.
I think this will fix https://github.com/zchee/docker-machine-driver-xhyve/issues/99
[NFS Reference](http://docstore.mik.ua/orelly/unix3/mac/ch03_10.htm)
> Set the NFS export to map all the users on the remote to the current user

- xhyve/xhyve.go
If you use a custom boot2docker URL, there will be no caching. This
means there is no cache file, so the os.Stat call will fail.
> Add error checking to CopyIsoToMachineDir.

- README.md
The readme still suggests you need a custom boot2docker iso for virtio9p support.  However, the changes were merged into boot2docker as of the 1.10.2 release, so the custom iso is no longer necessary for newer versions.
> Changed doc to reflect that virtio-9p support is included in the newer releases of boot2docker

- .travis.yml
~~`1.7rc5` is wait for travis-ci/gimme update....~~
> CI: upgrade TravisCI go version to 1.6.3 and 1.7rc5

- vmnet/vmnet.go
- xhyve/xhyve.go
This changes the extract function to just copy everything it can find, and it moves the detection into the getXhyveArgs function.
What do you think of this approach?
Ref #140
> Auto-detect whether the kernel is bzImage or vmlinuz.

- .travis.yml
Add
- `brew install opam libev`
- Initialize opam environment
- Install `qcow-format` and depends on package
for statically linked pre-build binary.
> ci/travis: add setup opam and libev for ocaml-qcow

- xhyve/xhyve.go
This patch will create a command line option to specify location for kernel and initrd files and set default `boot` so that it will not break any existing functionality.  
Use case: Now to use a centos live iso (which have docker configured) can consume it with docker machine.
```
docker-machine -D create centos -d xhyve --xhyve-boot2docker-url=file:/Users/prkumar/live-centos.iso --xhyve-boot-cmd "loglevel=3 root=live:CDLABEL=live-centos user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 base host=boot2docker" --xhyve-boot-location "isolinux"
```
> Fix #146 Make /boot configurable to allow different live iso to work with driver

- .gitignore
- xhyve/xhyve.go
@zchee please do a review. I tested with boot2docker, minikube and centos all works as expected. I am still a golang newbie so code might be not so appealing but happy to improve as per suggestion.
Also tested with ubuntu and get error message as expected.
```
(ubuntu) DBG | Extracting Kernel Options
Error creating machine: Error in driver during machine creation: Not abled to parse isolinux.cfg, Please use --xhyve-boot-cmd option
```
> Fix #150 Extract kernel options from the syslinux.conf file if exist

- circle.yml
This project has been enabled macOS build environment on CircleCI.
Change `circle.yml` to the macOS testing instead of docker testing.
We should disable macOS test on travis-ci because too slow of build start. But also need to consider the pre-compile binary deploy way.
> ci/circle: update circle.yml to macOS based build environment

- xhyve/xhyve.go
If we don't wait for the IP before setting up mounts, theres a chance
that the host isn't ready before we try to set up the 9p mount
ref https://github.com/kubernetes/minikube/issues/1133#issuecomment-282078827
> Wait for IP before setting up mounts

- xhyve/xhyve.go
This adds a new storage option - "raw disks".
In testing, the "raw disk" storage method seems to be about 10 times faster for our use case than the `ahci-hd` method. I'm not certain as to why, but I have heard that `virtio-blk` is supposedly lower overhead.
I followed the existing standard provided for `Qcow2` and the default `ahci-hd` method for implementing this.
To actually create the volume, we simply create a file, close it, then truncate it to the size that we want.
For mounting it, we just use `virtio-blk`.
I have confirmed this works with minikube, by setting `RawDisk` to true manually in my own minikube binary.
@zchee for review
> Add support for using a raw disk for storage

- xhyve/xhyve.go
The docker user ID is currently hardcoded to 1000, which is causing issues: https://github.com/kubernetes/minikube/issues/1374
I believe this is because there is a race condition in which user is created first (docker or rkt).
We may want to make this take an option for which username (docker or rkt) but I think that it would be expected by most uses for these files to be owned by the docker user, since that is the user they'll be logging in as.
FYI @zchee
> Don't hardcode the docker user id

- README.md
@zchee readme update as requested for https://github.com/zchee/docker-machine-driver-xhyve/pull/169
> Update readme to document rawdisk

- xhyve/xhyve.go
The 9p mount already exists in this case.  This is reverting back to a similar behavior before
https://github.com/zchee/docker-machine-driver-xhyve/pull/161/files
This now logs a warning, but this is a not fatal error on a recreate.  I'm not sure there's
a cleaner way since Start() has no context of if it is called on new VM or a recently stopped VM.
Reference: https://github.com/kubernetes/minikube/issues/1400#issuecomment-298503774
> Ignore setupmounts

- .travis.yml
~Update opam packages dependency to latest.~
~See also: https://github.com/moby/hyperkit#building~
version locked io-page to 1.6.1.
> ci/travis: fix opam install packages to locked io-page to 1.6.1

- main.go
See this PR for a summary of how much faster this makes starting minikube:
https://github.com/kubernetes/minikube/pull/1731
> Use the native docker-machine SSH driver.

- README.md
- xhyve/xhyve.go
Added the ability to setup multiple NFS Shares
By default (changeable with `xhyve-experimental-nfs-share-root`, see below) NFS shares are rooted at /xhyve-nfsshares to avoid the situation where a NFS Share `/usr` would be mounted at `/usr`
2 backward incompatible changes:
- renamed `xhyve-experimental-nfs-share` to `xhyve-experimental-nfs-share-enable`
- change `xhyve-experimental-nfs-share` from being a boolean to a string slice taking multiple path to be shared via NFS
- NFS Shares are now mounted under a default directory /xhyve-nfsshares (the old code was mounting everything under `/` causing, for example, `/usr` to be mounted at `/usr`)
Other change:
- add `xhyve-experimental-nfs-share-root` to allow specifying where in the guest the NFS Shares will be rooted at
Here's an example of …
> Multiple NFS shares

- README.md
- xhyve/xhyve.go
I have been working those past few days on `xhyve`'s ability to mount **multiple** folders from the Host to the Guest, either via **NFS** or via **Virtio9p**.
At this point, the NFS work has already been merged into master: https://github.com/zchee/docker-machine-driver-xhyve/pull/121
Since this last PR (#121), I have been working on allowing multiple mount point using Virtio9p, and have submitted a PR currently waiting for approval: https://github.com/zchee/docker-machine-driver-xhyve/pull/194. Until that point, `xhyve`'s was "hardcodingly" mounting the Host `/Users` folder into the Guest via Virtio9p, and the user had no choice in the matter.
At the same time, I have been working on modifying `minikube` (https://github.com/kubernetes/minikube) to allow `minikube` users to create …
> NFS and Virtio9p mounts setup refactoring
